project_id = "jvxdyfgjudycpopepgku"

[functions.sitemap-posts]
verify_jwt = false

[functions.sitemap-news]
verify_jwt = false

[functions.fetch-linkedin-embed]
verify_jwt = false

[functions.ping-sitemap]
verify_jwt = false

[functions.sitemap-jobs]
verify_jwt = false

[functions.prerender-meta]
verify_jwt = false
